[Fix] fix: modify randomNonce role
social-tw/social-tw-website pull request #270
Opened 2024-01-18 18:12 UTC by UranusLin

## Summary

This PR updates the randomNonce function to correctly generate nonces based on the user's action count. It ensures that the first three nonces (0, 1, 2) are used in order for the initial three actions, and subsequent actions receive a randomly chosen nonce within the same range.

## Linked Issue

fix #269 

## Details

- Updated `randomNonce` to consider the action count before deciding whether to return a sequential nonce or a random nonce.
- Imported `NUM_EPOCH_KEY_NONCE_PER_EPOCH` from config to use as the upper limit for nonce generation.

## Impacted Areas

- `packages/frontend/src/utils/randomNonce.ts`
- `packages/frontend/src/__tests__/utils/randomNonce.test.ts`

## Tests

- Unit tests have been updated in randomNonce.test.ts to cover the new logic.
- Tests ensure the function returns sequential nonces for the first three actions and random nonces thereafter.
- No specific environment or configuration needed apart from the standard project setup.

## Possible Impacts

- This change ensures more predictable and correct nonce generation for the first three user actions, impacting how the application handles these initial transactions.
- No backward compatibility issues are expected.

## Visual Materials

N/A

## Verification Steps

- Run the updated unit tests in randomNonce.test.ts to verify the correct function behavior.
- Integrate the function into the frontend and perform manual testing to observe nonce generation based on action counts.

## Todo

Break down the progress of the PR for everyone to see what else you intend to include in this PR.

-   [x] Update randomNonce function logic.
-   [x] Update and verify unit tests for randomNonce.

## Checklist

-   [x] All new and existing tests pass
-   [x] I have updated the documentation (if applicable)
-   [x] My changes do not introduce new security vulnerabilities
-   [x] Run `yarn lint:fix`

2024-01-24 09:21 UTC, vivianjeng requested changes
I encountered this error when posting
```
PostList.tsx:221 Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:16227:9)
    at useContext (react.development.js:1619:21)
    at useUser (User.tsx:312:42)
    at useActionCount (useActionCount.ts:46:26)
    at randomNonce (randomNonce.ts:14:52)
    at eval (useCreatePost.ts:63:47)
    at Generator.next (<anonymous>)
    at fulfilled (useCreatePost.ts:12:24)
```

please check

2024-01-24 11:05 UTC, kittybest commented
I think the `randomNonce()` should also be called inside `createComment` hook?

2024-01-24 11:08 UTC, kittybest commented on packages/frontend/src/utils/randomNonce.ts
Could be changed to 
```ts
export default function randomNonce(actionCount: number) {
    if (actionCount < NUM_EPOCH_KEY_NONCE_PER_EPOCH) {
        return actionCount
    }

    return Math.floor(Math.random() * NUM_EPOCH_KEY_NONCE_PER_EPOCH)
}
```
This is only a logic function, no need to call any hook or context.

2024-05-06 01:17 UTC, Xiawpohr commented on packages/frontend/src/utils/randomNonce.ts
Fixed

2024-05-06 01:18 UTC, Xiawpohr commented on packages/frontend/src/config.ts
> +export const NUM_EPOCH_KEY_NONCE_PER_EPOCH = 3
We can open an issue about this on Notion

2024-05-06 01:23 UTC, Xiawpohr commented on packages/frontend/src/config.ts
> +export const NUM_EPOCH_KEY_NONCE_PER_EPOCH = 3
Issue link: https://www.notion.so/Get-EpochKey-amount-per-epoch-from-api-config-ca956cae20554c2ebbf1aa7fd82f7750?pvs=4

2024-05-06 01:33 UTC, Xiawpohr commented
@vivianjeng I already fixed this issue. I change the function name from `randomNonce` to `getEpochKeyNonce` and remove hook in it. Please review changes again. Thanks.

2024-05-07 02:51 UTC, vivianjeng commented
<img width="523" alt="截圖 2024-05-07 上午10 49 23" src="https://github.com/social-tw/social-tw-website/assets/17507085/76fda24a-a863-4276-ba8f-a015411d7b79">

I still get the same epoch key at the 2nd and 3rd post.

2024-05-07 03:09 UTC, vivianjeng commented
I printed out the action count and the nonce, but the behavior is weird. please check
```js
// post 1
action count 0
useCreatePost.ts:81 nonce 2
// post 2
useCreatePost.ts:79 action count 0
useCreatePost.ts:81 nonce 1
// post 3
useCreatePost.ts:79 action count 2
useCreatePost.ts:81 nonce 1
 
```

2024-05-10 09:50 UTC, vivianjeng approved these changes
need to change user state

2024-05-10 10:10 UTC, merged