[UST-277] [Circuit] Check if reputation is negative and the epoch last claimed proof < 1 day
social-tw/social-tw-website pull request #588
Opened 2024-12-04 01:58 UTC by chentihe

## Summary

新增 dailyClaimTemplate，在此circuit內驗證

- reputation proof 是否正確
- 用戶的reputation < 0
- daily claim nullifier 是否正確
- 
public signals需要有以下這些內容，以利後端跟合約進行檢查
- dailyEpoch
- dailyNullifier
- attesterId
- epoch
- minRep
- maxRep

## Linked Issue

close #580 

## Tests
     * 1. should succeed with valid inputs
     * 2. should revert with reputation > 0
     * 3. should revert with wrong reputation proof
     * 4. should revert with wrong daily nullifier

## Checklist

-   [x] All new and existing tests pass
-   [x] I have updated the documentation (if applicable)
-   [x] My changes do not introduce new security vulnerabilities

2024-12-04 07:15 UTC, cc03668 commented
@chentihe 這個 PR 名稱請遵守規範做修改唷

2024-12-18 08:48 UTC, FoodChain1028 requested changes
I didn't see where the circuit check if the last epoch claimed is less than 24 hours :(. Maybe I just miss it. Could you point it out where it is? Thanks!

2024-12-18 08:48 UTC, FoodChain1028 commented on packages/circuits/test/proveDailyClaim.test.ts
> +     * 4. should revert with wrong daily nullifier
Can we add other tests to test: when user get a reputation after claiming a daily rep, and the user claim again within 24 hour?

And I don't know how do you check if **the epoch last claimed** is < 1 day. (I didn't see the check in circuit).

2024-12-18 10:21 UTC, FoodChain1028 approved these changes
LGTM. Just make sure the `1 day check` test will be included in the contract part, thanks!

2024-12-18 13:25 UTC, merged