[WIP][Contract][UST-196] Check if reputation is negative and the epoch last claimed proof < 1 day
social-tw/social-tw-website pull request #601
Opened 2024-12-24 01:17 UTC by chentihe

Please follow the guidelines in [Contribution.md](https://github.com/social-tw/social-tw-website/blob/main/CONTRIBUTING.md) first, then start to create your pull request here.

## Summary

Describe the changes made in your pull request here.

## Linked Issue

close #579 

## Details

Any implementation detail worth pointing out, if any.

## Impacted Areas

List the files or modules that this PR will change.

## Tests

Mention all types of tests (unit, integration, performance, etc.) that you've carried out and if any specific environment or configuration is needed to run them.

## Possible Impacts

Describe any existing features that might be affected by this change, or any potential backward compatibility issues, if any.

## Visual Materials

If your changes have UI effects, consider attaching screenshots or videos to demonstrate them.

## Verification Steps

Provide a step-by-step guide for others to reproduce your results and verify your changes.

## Todo

Break down the progress of the PR for everyone to see what else you intend to include in this PR.

-   [ ] Draft implementation for `function`
-   [ ] Unit tests for `function`

## Checklist

-   [ ] All new and existing tests pass
-   [ ] I have updated the documentation (if applicable)
-   [ ] My changes do not introduce new security vulnerabilities

2024-12-24 09:01 UTC, kittybest commented on packages/contracts/abi/UnirepApp.json
> +    { "inputs": [], "name": "NonNegetativeReputation", "type": "error" },
nit: `NonNegetativeReputation` -> `NonNegativeReputation`? 下面同理

2024-12-24 10:45 UTC, vivianjeng commented on packages/contracts/contracts/UnirepApp.sol
> +        }
I found that there is a bug in the circuit
To prove the reputation is negative
you should prove `data[1] > data[0]`
or you can choose to prove `maxRep > 0` and `proveMaxRep > 0`
`maxRep` means `data[1] - data[0] >= maxRep`
See https://github.com/Unirep/Unirep/blob/36e5adf8c1eaa7398716ff3653327d5bd98181b3/packages/circuits/circuits/reputation.circom#L146

2025-01-14 09:53 UTC, FoodChain1028 requested changes
There are several things need to be changed :) Thank you for the work!

2025-01-14 09:53 UTC, FoodChain1028 commented on packages/contracts/test/ClaimDailyLoginRep.test.ts
>  import { ethers } from 'hardhat'
nit : recommend to put this below `// @ts-ignore` to prevent the complaining of compiler

2025-01-14 09:53 UTC, FoodChain1028 commented on packages/contracts/test/ClaimDailyLoginRep.test.ts
>      const REG_REP = 10
nit: 

```suggestion
    const NEG_REP = 10
```

2025-01-14 09:53 UTC, FoodChain1028 commented on packages/contracts/test/ClaimDailyLoginRep.test.ts
>  describe('Claim Daily Login Reputation Test', function () {
can you add more tests here:

1. a user with `rep<0` cannot claim the login rep again within 1 day.
2. after the a user with `rep<0` claim the login rep and his reputation become 0 => the user cannot claim
3. a user with `rep>0` cannot claim => attest neg_rep to the user => the user can claim

2025-01-14 09:53 UTC, FoodChain1028 commented on packages/relay/src/services/ReputationService.ts
> +        publicSignals: any,
would be better to have those types

2025-01-14 09:53 UTC, FoodChain1028 commented on packages/relay/test/checkin.test.ts
>  describe('POST /api/checkin', function () {
when I running the relay checkin test, I met this error (?) I think this might be irrevelant to this :(

```bash
Sending tx 0x26c85fca44636b70c53ab0d091ab48e8482b8f310b4c8aa0d5131e294e6b50f3
    1) "before all" hook for "should allow users with negative reputation to claim reputation"
server checkin is shutting down
all sockets closed
server closed checkin


  0 passing (18s)
  1 failing

  1) POST /api/checkin
       "before all" hook for "should allow users with negative reputation to claim reputation":

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at signUp (test/utils/signup.ts:28:25)
      at async Context.<anonymous> (test/checkin.test.ts:61:27)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js run test ./test/checkin.test.ts
Directory: /Users/foodchain/Documents/unirep-social-tw/social-tw-website/packages/relay
Output:
```

2025-01-15 13:45 UTC, chentihe commented on packages/contracts/contracts/UnirepApp.sol
> +    function dailyEpochRemainingTime() public view returns (uint48) {
this function is not used now, just in case that the client side may need to display the next claim daily rep time.

2025-01-16 16:59 UTC, FoodChain1028 approved these changes
Looks great to me! 

just one typo remained.

2025-01-21 00:41 UTC, merged